import 'package:flutter/material.dart';
import '../app.dart';
import '../models/money_transaction.dart';
import '../models/region_profile.dart';
import '../services/local_store.dart';

class AddTransactionPage extends StatefulWidget {final LocalStore store;final RegionProfile profile;final MoneyTransactionType type;final String? initialCategory;const AddTransactionPage({super.key,required this.store,required this.profile,required this.type,this.initialCategory});@override State<AddTransactionPage> createState()=>_State();}
class _State extends State<AddTransactionPage>{final amount=TextEditingController(),desc=TextEditingController(),notes=TextEditingController();late String category;DateTime date=DateTime.now();
 @override void initState(){super.initState();category=widget.initialCategory??(widget.type==MoneyTransactionType.income?'Salary':'Groceries');}
 @override Widget build(BuildContext context){final cats=widget.type==MoneyTransactionType.income?incomeCategories:expenseCategories;return Scaffold(appBar:AppBar(title:Text(widget.type==MoneyTransactionType.income?'Add Income':'Add Expense')),body:ListView(padding:const EdgeInsets.all(18),children:[DropdownButtonFormField<String>(initialValue:category,decoration:const InputDecoration(labelText:'Category'),items:cats.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>category=v??category)),const SizedBox(height:12),TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:'Amount (${effectiveCurrencyCode(widget.store,widget.profile)})',prefixIcon:const Icon(Icons.payments_rounded))),const SizedBox(height:12),TextField(controller:desc,decoration:const InputDecoration(labelText:'Shop / Description',prefixIcon:Icon(Icons.storefront_rounded))),const SizedBox(height:12),TextField(controller:notes,maxLines:2,decoration:const InputDecoration(labelText:'Notes (optional)')),const SizedBox(height:22),FilledButton(onPressed:()async{final v=double.tryParse(amount.text.trim());if(v==null||v<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter a valid amount.')));return;}await widget.store.addTransaction(MoneyTransaction(id:DateTime.now().microsecondsSinceEpoch.toString(),date:date,type:widget.type,category:category,description:desc.text.trim(),amount:v,notes:notes.text.trim()));if(context.mounted)Navigator.pop(context);},style:FilledButton.styleFrom(backgroundColor:kNeviroGreen,padding:const EdgeInsets.all(16)),child:const Text('Save'))]));}}
