import 'package:flutter/material.dart';
import '../app.dart';import '../models/money_transaction.dart';import '../models/region_profile.dart';import '../models/station_price.dart';import '../services/local_store.dart';
import 'add_fuel_page.dart';import 'add_transaction_page.dart';import 'fuel_prices_page.dart';import 'home_page.dart';import 'reports_page.dart';import 'settings_page.dart';
class AppShell extends StatefulWidget{final LocalStore store;final RegionProfile profile;const AppShell({super.key,required this.store,required this.profile});@override State<AppShell> createState()=>_State();}
class _State extends State<AppShell>{int index=0;
 Future<void> fuel({StationPrice? station})=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AddFuelPage(store:widget.store,profile:widget.profile,suggestedStation:station)));
 Future<void> tx(MoneyTransactionType type)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AddTransactionPage(store:widget.store,profile:widget.profile,type:type)));
 void addMenu(){showModalBottomSheet(context:context,builder:(ctx)=>SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(leading:const Icon(Icons.remove_circle_outline),title:const Text('Add Expense'),onTap:(){Navigator.pop(ctx);tx(MoneyTransactionType.expense);}),ListTile(leading:const Icon(Icons.add_circle_outline),title:const Text('Add Income'),onTap:(){Navigator.pop(ctx);tx(MoneyTransactionType.income);}),ListTile(leading:const Icon(Icons.local_gas_station_rounded),title:const Text('Add Fuel'),onTap:(){Navigator.pop(ctx);fuel();})]))));}
 @override Widget build(BuildContext context){final pages=[HomePage(store:widget.store,profile:widget.profile,onOpenFuelPrices:()=>setState(()=>index=1),onAddFuel:()=>fuel(),onAddExpense:()=>tx(MoneyTransactionType.expense),onAddIncome:()=>tx(MoneyTransactionType.income)),FuelPricesPage(store:widget.store,profile:widget.profile,active:index==1,onUseForFillUp:(s)=>fuel(station:s)),ReportsPage(store:widget.store,profile:widget.profile),SettingsPage(store:widget.store,profile:widget.profile)];return Scaffold(body:SafeArea(child:IndexedStack(index:index,children:pages)),bottomNavigationBar:BottomNavigationBar(type:BottomNavigationBarType.fixed,currentIndex:index>1?index+1:index,selectedItemColor:kNeviroGreenDark,unselectedItemColor:kNeviroMuted,onTap:(i){if(i==2){addMenu();return;}setState(()=>index=i>2?i-1:i);},items:const [BottomNavigationBarItem(icon:Icon(Icons.home_rounded),label:'Home'),BottomNavigationBarItem(icon:Icon(Icons.local_gas_station_rounded),label:'Fuel'),BottomNavigationBarItem(icon:Icon(Icons.add_circle,size:34),label:'Add'),BottomNavigationBarItem(icon:Icon(Icons.bar_chart_rounded),label:'Reports'),BottomNavigationBarItem(icon:Icon(Icons.settings_rounded),label:'Settings')]));}}
